title: Soumyodeep Dey
name: Soumyodeep Dey
description: Master's student in Artificial Intelligence at IIT Delhi
url: https://soumyodeepdey.github.io
baseurl: ""
repository: soumyodeepdey/soumyodeepdey.github.io

author:
  name: Soumyodeep Dey
  avatar: #/assets/images/soumyodeep-dey-photo.jpeg
  bio: "Pursuing a Master's in AI at IIT Delhi, researching Large Language Models and Graph Neural Networks."
  location: Delhi, India
  email: "soumyodeepdey96@gmail.com"
  linkedin: "https://www.linkedin.com/in/welcome-to-the-profile-of-soumyodeep/"
  github: "knightwalker96"
  google_scholar: "https://scholar.google.com/citations?user=4gA_CyIAAAAJ&hl=en"

# Other settings (leave unchanged unless needed)
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default
locale: en-US
search: true
analytics:
  provider: false
